Test.expect(solution('XXI') == 21, 'XXI should == 21')
Test.expect(solution('I') == 1, 'I should == 1')
Test.expect(solution('IV') == 4, 'IV should == 4')
Test.expect(solution('MMVIII') == 2008, 'MMVIII should == 2008')
Test.expect(solution('MDCLXVI') == 1666, 'MDCLXVI should == 1666')