ren "Descriptive selections of data" "050_Descriptive selections of data"
ren "The reject() function" "049_The reject() function"
ren "UriBuilder" "048_UriBuilder"
ren "Imperfect Network #2 (out-of-order messages)" "047_Imperfect Network #2 (out-of-order messages)"
ren "Codewar's style ranking system" "046_Codewar's style ranking system"
ren "Reverse words" "045_Reverse words"
ren "Base64 Encoding" "044_Base64 Encoding"
ren "Longest Common Subsequence" "043_Longest Common Subsequence"
ren "Pick peaks" "042_Pick peaks"
ren "Hard Time Bomb" "041_Hard Time Bomb"
ren "Finding an appointment" "040_Finding an appointment"
ren "Human readable duration format" "039_Human readable duration format"
ren "Nesting Structure Comparison" "038_Nesting Structure Comparison"
ren "Spy Function" "037_Spy Function"
ren "Process trees" "036_Process trees"
ren "Factorial Factory" "035_Factorial Factory"
ren "PaginationHelper" "034_PaginationHelper"
ren "Pete, the baker (part 2)" "033_Pete, the baker (part 2)"
ren "Title Case" "032_Title Case"
ren "Strip Url Params" "031_Strip Url Params"
ren "Name Your Space" "030_Name Your Space"
ren "IP Validation" "029_IP Validation"
ren "Roman Numerals Decoder" "028_Roman Numerals Decoder"
ren "parseInt() reloaded" "027_parseInt() reloaded"
ren "Adding Big Numbers" "026_Adding Big Numbers"
ren "Object extend" "025_Object extend"
ren "Break camelCase" "024_Break camelCase"
ren "search in multidimensional array" "023_search in multidimensional array"
ren "Number Zoo Patrol" "022_Number Zoo Patrol"
ren "Secret knock" "021_Secret knock"
ren "How many in the array." "020_How many in the array."
ren "Multiples of 3 and 5" "019_Multiples of 3 and 5"
ren "Valid Parentheses" "018_Valid Parentheses"
ren "RGB To Hex Conversion" "017_RGB To Hex Conversion"
ren "Is a number prime?" "016_Is a number prime?"
ren "Snail" "015_Snail"
ren "Sort arrays - 1" "014_Sort arrays - 1"
ren "Get key/value pairs as arrays" "013_Get key/value pairs as arrays"
ren "Limit string length - 1" "012_Limit string length - 1"
ren "Don't rely on luck." "011_Don't rely on luck."
ren "Part 1: Evil Programming Government Restrictions" "010_Part 1: Evil Programming Government Restrictions"
ren "Valid Braces" "009_Valid Braces"
ren "Triangular Treasure" "008_Triangular Treasure"
ren "(Don't) Make Me Repeat Myself" "007_(Don't) Make Me Repeat Myself"
ren "getNames()" "006_getNames()"
ren "String ends with?" "005_String ends with?"
ren "Elapsed Seconds" "004_Elapsed Seconds"
ren "No oddities here" "003_No oddities here"
ren "Multiply" "002_Multiply"
--ren  "Broken Greetings" "001_Broken Greetings"